"""sample path

Revision ID: a76a07061e4c
Revises: 
Create Date: 2020-10-04 14:48:03.361898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76a07061e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('sample_path', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'node', ['data'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node', type_='unique')
    op.drop_column('node', 'sample_path')
    # ### end Alembic commands ###
